# Site metadata
title: Code Blocks
author:
  name: Built by Alex Forsythe
permalink: pretty

# Minima
remote_theme: jekyll/minima
minima:
  skin: auto
  nav_pages:
    - privacy-policy.md
    - terms-of-service.md
    - contributing.md
  hide_site_feed_link: true
  social_links:
    - title: GitHub
      icon: github
      url: https://github.com/alexwforsythe/code-blocks
google_analytics: G-WB3EH6CCYD

titles_from_headings:
  enabled: true
  strip_title: true

plugins:
  - jekyll-remote-theme
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-sitemap
